package motion

import (
	"strings"
	"testing"
	"unicode/utf8"
)

// flatPos returns the flat buffer position for (line, col) in the joined text.
func flatPos(lines []string, line, col int) int {
	p := 0
	for i := range line {
		p += len([]rune(lines[i])) + 1 // +1 for \n
	}
	return p + col
}

// cursorLine returns which line index pos falls on, based on the lines array.
func cursorLine(text []rune, lines []string, pos int) int {
	if len(lines) == 0 {
		return 0
	}
	n := len(text)
	if n > 0 && text[n-1] == '\n' && pos == n {
		return len(lines) - 1
	}
	if pos >= n {
		pos = n - 1
	}
	if pos < 0 {
		return 0
	}
	line := 0
	for i := 0; i < pos; i++ {
		if text[i] == '\n' {
			line++
		}
	}
	return line
}

// deleteLine returns the text produced by deleting the line at lineIdx.
func deleteLine(lines []string, lineIdx int) string {
	if lineIdx < 0 || lineIdx >= len(lines) {
		return strings.Join(lines, "\n")
	}
	dst := make([]string, 0, len(lines)-1)
	dst = append(dst, lines[:lineIdx]...)
	dst = append(dst, lines[lineIdx+1:]...)
	return strings.Join(dst, "\n")
}

func FuzzMotionConsistency(f *testing.F) {
	// Seed corpus: challenging structural scenarios
	seeds := []string{
		"a",
		"a\n",
		"\n",
		"a\nb",
		"a\n\n",
		"a\nb\n",
		"a\n\nb",
		"\n\n",
		"\na",
		"ab\n\nxy",
		"line1\n\nline3", // Include our controversial case in seeds
	}
	for _, s := range seeds {
		f.Add(s)
	}

	f.Fuzz(func(t *testing.T, s string) {
		// Ignore invalid UTF-8 generated by the fuzzer
		if !utf8.ValidString(s) {
			return
		}

		lines := strings.Split(s, "\n")

		if len(lines) > 6 || len(lines) == 0 {
			return
		}
		for _, l := range lines {
			if len([]rune(l)) > 10 {
				return
			}
		}

		text := []rune(s)

		for lineIdx, lineStr := range lines {
			line := []rune(lineStr) // evaluate current line as runes
			for col := 0; col <= len(line); col++ {
				pos := flatPos(lines, lineIdx, col)
				if pos > len(text) {
					continue
				}

				// --- j: move down ---
				if lineIdx+1 < len(lines) {
					next := []rune(lines[lineIdx+1])
					maxTargetCol := len(next)
					if maxTargetCol > 0 {
						maxTargetCol--
					}
					tcol := min(col, maxTargetCol)
					want := flatPos(lines, lineIdx+1, tcol)
					got := MoveDown(text, pos, 1)
					if got != want {
						t.Errorf("j: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got, want)
					}
				}

				// --- k: move up ---
				if lineIdx > 0 {
					prev := []rune(lines[lineIdx-1])
					maxTargetCol := len(prev)
					if maxTargetCol > 0 {
						maxTargetCol--
					}
					tcol := min(col, maxTargetCol)
					want := flatPos(lines, lineIdx-1, tcol)
					got := MoveUp(text, pos, 1)
					if got != want {
						t.Errorf("k: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got, want)
					}
				}

				if pos >= len(text) {
					continue
				}

				// --- h: move left ---
				if col > 0 {
					want := flatPos(lines, lineIdx, col-1)
					var e Engine
					got := e.Process(text, pos, Key('h'))
					if got.Kind != ResultNavigate || got.Cursor != want {
						t.Errorf("h: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got.Cursor, want)
					}
				} else {
					var e Engine
					got := e.Process(text, pos, Key('h'))
					if got.Kind != ResultNavigate || got.Cursor != pos {
						t.Errorf("h at start: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got.Cursor, pos)
					}
				}

				// --- l: move right ---
				if col < len(line)-1 {
					want := flatPos(lines, lineIdx, col+1)
					var e Engine
					got := e.Process(text, pos, Key('l'))
					if got.Kind != ResultNavigate || got.Cursor != want {
						t.Errorf("l: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got.Cursor, want)
					}
				} else {
					var e Engine
					got := e.Process(text, pos, Key('l'))
					if got.Kind != ResultNavigate || got.Cursor != pos {
						t.Errorf("l at end: lines=%q from=(%d,%d) pos=%d got=%d want=%d",
							lines, lineIdx, col, pos, got.Cursor, pos)
					}
				}

				// --- dd: delete line ---
				lineIdxOp := cursorLine(text, lines, pos)
				wantText := deleteLine(lines, lineIdxOp)
				var e2 Engine

				r1 := e2.Process(text, pos, Key('d'))
				if r1.Kind != ResultNone {
					t.Errorf("dd first d: lines=%q pos=%d kind=%v want ResultNone", lines, pos, r1.Kind)
					continue
				}

				r2 := e2.Process(text, pos, Key('d'))
				if r2.Kind != ResultExecute {
					t.Errorf("dd second d: lines=%q pos=%d kind=%v want ResultExecute", lines, pos, r2.Kind)
					continue
				}
				if r2.Op != OpDelete {
					t.Errorf("dd: got Op=%v want OpDelete", r2.Op)
					continue
				}

				ar := ApplyOp(r2.Op, text, pos, r2.Range)
				gotText := string(ar.Text)
				if gotText != wantText {
					t.Errorf("dd: input=%q pos=%d lines=%q got=%q want=%q", string(text), pos, lines, gotText, wantText)
				}
			}
		}
	})
}
